//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBusiness.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitasMedicas
    {
        public int IdCita { get; set; }
        public string ProfesionalSalud { get; set; }
        public string Especialidad { get; set; }
        public string Sede { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string CodigoCita { get; set; }
        public Nullable<bool> Asistencia { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> PacienteDocumento { get; set; }
    }
}
