//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBusiness.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int IdClient { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int NumeroDocumento { get; set; }
        public int TipDocumento { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
