//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBusiness.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesionalSalud
    {
        public int Id { get; set; }
        public Nullable<int> NumeroDocumento { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
        public string Especialidad { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FecharCreacion { get; set; }
        public string NumeroLicencia { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
    }
}
